export default {
  billingAddress: 'billing_address',
  billingCity: 'billing_address.city',
  billingLine1: 'billing_address.line1',
  billingLine2: 'billing_address.line2',
  billingPostalCode: 'billing_address.postal_code',
  billingState: 'billing_address.state',
  email: 'email',
  firstName: 'first_name',
  lastName: 'last_name',
  optedIntoMarketing: 'opted_into_marketing',
  sameShipping: 'same_shipping',
  phoneNumber: 'phone_number',
  shippingAddress: 'shipping_address',
  shippingCity: 'shipping_address.city',
  shippingLine1: 'shipping_address.line1',
  shippingLine2: 'shipping_address.line2',
  shippingPostalCode: 'shipping_address.postal_code',
  shippingState: 'shipping_address.state',
  tokenizedCreditCardNum: 'tokenized_credit_card_num'
};
